######################################################################
# Automatically generated by qmake (2.01a) ? 4? 11 16:59:10 2008
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += testdialog.h
FORMS += testdialog.ui
SOURCES += main.cpp testdialog.cpp
