# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'testdialog.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_TestDialog(object):
    def setupUi(self, TestDialog):
        TestDialog.setObjectName("TestDialog")
        TestDialog.resize(275, 219)
        self.vboxlayout = QtWidgets.QVBoxLayout(TestDialog)
        self.vboxlayout.setObjectName("vboxlayout")
        self.gridlayout = QtWidgets.QGridLayout()
        self.gridlayout.setObjectName("gridlayout")
        self.label = QtWidgets.QLabel(TestDialog)
        self.label.setObjectName("label")
        self.gridlayout.addWidget(self.label, 0, 0, 1, 1)
        self.lineEdit = QtWidgets.QLineEdit(TestDialog)
        self.lineEdit.setObjectName("lineEdit")
        self.gridlayout.addWidget(self.lineEdit, 0, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(TestDialog)
        self.label_2.setObjectName("label_2")
        self.gridlayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.hboxlayout = QtWidgets.QHBoxLayout()
        self.hboxlayout.setObjectName("hboxlayout")
        self.horizontalSlider = QtWidgets.QSlider(TestDialog)
        self.horizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider.setObjectName("horizontalSlider")
        self.hboxlayout.addWidget(self.horizontalSlider)
        self.spinBox = QtWidgets.QSpinBox(TestDialog)
        self.spinBox.setObjectName("spinBox")
        self.hboxlayout.addWidget(self.spinBox)
        self.gridlayout.addLayout(self.hboxlayout, 1, 1, 1, 1)
        self.hboxlayout1 = QtWidgets.QHBoxLayout()
        self.hboxlayout1.setObjectName("hboxlayout1")
        self.checkBox = QtWidgets.QCheckBox(TestDialog)
        self.checkBox.setObjectName("checkBox")
        self.hboxlayout1.addWidget(self.checkBox)
        self.pushButton = QtWidgets.QPushButton(TestDialog)
        self.pushButton.setObjectName("pushButton")
        self.hboxlayout1.addWidget(self.pushButton)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.hboxlayout1.addItem(spacerItem)
        self.gridlayout.addLayout(self.hboxlayout1, 2, 0, 1, 2)
        self.vboxlayout.addLayout(self.gridlayout)
        self.color_group = QtWidgets.QGroupBox(TestDialog)
        self.color_group.setCheckable(True)
        self.color_group.setObjectName("color_group")
        self.hboxlayout2 = QtWidgets.QHBoxLayout(self.color_group)
        self.hboxlayout2.setObjectName("hboxlayout2")
        self.rgb_radio = QtWidgets.QRadioButton(self.color_group)
        self.rgb_radio.setObjectName("rgb_radio")
        self.hboxlayout2.addWidget(self.rgb_radio)
        self.cmyk_radio = QtWidgets.QRadioButton(self.color_group)
        self.cmyk_radio.setObjectName("cmyk_radio")
        self.hboxlayout2.addWidget(self.cmyk_radio)
        self.yuv_radio = QtWidgets.QRadioButton(self.color_group)
        self.yuv_radio.setObjectName("yuv_radio")
        self.hboxlayout2.addWidget(self.yuv_radio)
        self.color_combo = QtWidgets.QComboBox(self.color_group)
        self.color_combo.setObjectName("color_combo")
        self.color_combo.addItem("")
        self.color_combo.addItem("")
        self.color_combo.addItem("")
        self.hboxlayout2.addWidget(self.color_combo)
        self.vboxlayout.addWidget(self.color_group)
        self.buttonBox = QtWidgets.QDialogButtonBox(TestDialog)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.NoButton|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.vboxlayout.addWidget(self.buttonBox)

        self.retranslateUi(TestDialog)
        self.horizontalSlider.valueChanged['int'].connect(self.spinBox.setValue)
        self.spinBox.valueChanged['int'].connect(self.horizontalSlider.setValue)
        self.checkBox.toggled['bool'].connect(self.pushButton.setEnabled)
        self.buttonBox.accepted.connect(TestDialog.accept)
        self.buttonBox.rejected.connect(TestDialog.reject)
        QtCore.QMetaObject.connectSlotsByName(TestDialog)

    def retranslateUi(self, TestDialog):
        _translate = QtCore.QCoreApplication.translate
        TestDialog.setWindowTitle(_translate("TestDialog", "Dialog"))
        self.label.setText(_translate("TestDialog", "그림"))
        self.label_2.setText(_translate("TestDialog", "채도"))
        self.checkBox.setText(_translate("TestDialog", "색반전하기"))
        self.pushButton.setText(_translate("TestDialog", "미리보기"))
        self.color_group.setTitle(_translate("TestDialog", "색상값 지정하기"))
        self.rgb_radio.setText(_translate("TestDialog", "RGB"))
        self.cmyk_radio.setText(_translate("TestDialog", "CMYK"))
        self.yuv_radio.setText(_translate("TestDialog", "YUV"))
        self.color_combo.setItemText(0, _translate("TestDialog", "RGB"))
        self.color_combo.setItemText(1, _translate("TestDialog", "CMYK"))
        self.color_combo.setItemText(2, _translate("TestDialog", "YUV"))

