# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainGUI.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1196, 910)
        MainWindow.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setObjectName("widget")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.widget)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.splitter = QtWidgets.QSplitter(self.widget)
        self.splitter.setOrientation(QtCore.Qt.Vertical)
        self.splitter.setObjectName("splitter")
        self.tabWidget_4 = QtWidgets.QTabWidget(self.splitter)
        self.tabWidget_4.setStyleSheet("")
        self.tabWidget_4.setObjectName("tabWidget_4")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setStyleSheet("")
        self.tab_3.setObjectName("tab_3")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.tab_3)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.comb_format = QtWidgets.QComboBox(self.tab_3)
        self.comb_format.setObjectName("comb_format")
        self.comb_format.addItem("")
        self.comb_format.addItem("")
        self.comb_format.addItem("")
        self.comb_format.addItem("")
        self.comb_format.addItem("")
        self.comb_format.addItem("")
        self.comb_format.addItem("")
        self.comb_format.addItem("")
        self.verticalLayout_2.addWidget(self.comb_format)
        self.tabWidget_4.addTab(self.tab_3, "")
        self.tabWidget_3 = QtWidgets.QTabWidget(self.splitter)
        self.tabWidget_3.setObjectName("tabWidget_3")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.tab_2)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.LineEdit_width = QtWidgets.QLineEdit(self.tab_2)
        self.LineEdit_width.setObjectName("LineEdit_width")
        self.horizontalLayout_2.addWidget(self.LineEdit_width)
        self.label = QtWidgets.QLabel(self.tab_2)
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        self.LineEdit_height = QtWidgets.QLineEdit(self.tab_2)
        self.LineEdit_height.setObjectName("LineEdit_height")
        self.horizontalLayout_2.addWidget(self.LineEdit_height)
        self.horizontalLayout_7.addLayout(self.horizontalLayout_2)
        self.apply_button = QtWidgets.QPushButton(self.tab_2)
        self.apply_button.setObjectName("apply_button")
        self.horizontalLayout_7.addWidget(self.apply_button)
        self.verticalLayout_5.addLayout(self.horizontalLayout_7)
        self.tabWidget_3.addTab(self.tab_2, "")
        self.tabWidget = QtWidgets.QTabWidget(self.splitter)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.tab)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.radiobutton_be = QtWidgets.QRadioButton(self.tab)
        self.radiobutton_be.setObjectName("radiobutton_be")
        self.horizontalLayout.addWidget(self.radiobutton_be)
        self.radiobutton_le = QtWidgets.QRadioButton(self.tab)
        self.radiobutton_le.setObjectName("radiobutton_le")
        self.horizontalLayout.addWidget(self.radiobutton_le)
        self.verticalLayout_4.addLayout(self.horizontalLayout)
        self.tabWidget.addTab(self.tab, "")
        self.group_rgb = QtWidgets.QGroupBox(self.splitter)
        self.group_rgb.setObjectName("group_rgb")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.group_rgb)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.checkbox_r = QtWidgets.QCheckBox(self.group_rgb)
        self.checkbox_r.setObjectName("checkbox_r")
        self.horizontalLayout_4.addWidget(self.checkbox_r)
        self.checkbox_g = QtWidgets.QCheckBox(self.group_rgb)
        self.checkbox_g.setObjectName("checkbox_g")
        self.horizontalLayout_4.addWidget(self.checkbox_g)
        self.checkbox_b = QtWidgets.QCheckBox(self.group_rgb)
        self.checkbox_b.setObjectName("checkbox_b")
        self.horizontalLayout_4.addWidget(self.checkbox_b)
        self.verticalLayout_6.addLayout(self.horizontalLayout_4)
        self.group_yuv = QtWidgets.QGroupBox(self.splitter)
        self.group_yuv.setTitle("")
        self.group_yuv.setObjectName("group_yuv")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.group_yuv)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.checkbox_y = QtWidgets.QCheckBox(self.group_yuv)
        self.checkbox_y.setChecked(False)
        self.checkbox_y.setTristate(True)
        self.checkbox_y.setObjectName("checkbox_y")
        self.horizontalLayout_6.addWidget(self.checkbox_y)
        self.checkbox_u = QtWidgets.QCheckBox(self.group_yuv)
        self.checkbox_u.setChecked(False)
        self.checkbox_u.setObjectName("checkbox_u")
        self.horizontalLayout_6.addWidget(self.checkbox_u)
        self.checkbox_v = QtWidgets.QCheckBox(self.group_yuv)
        self.checkbox_v.setChecked(False)
        self.checkbox_v.setObjectName("checkbox_v")
        self.horizontalLayout_6.addWidget(self.checkbox_v)
        self.verticalLayout_3.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.checkbox__a_yuv = QtWidgets.QCheckBox(self.group_yuv)
        self.checkbox__a_yuv.setObjectName("checkbox__a_yuv")
        self.horizontalLayout_5.addWidget(self.checkbox__a_yuv)
        self.checkbox_swap = QtWidgets.QCheckBox(self.group_yuv)
        self.checkbox_swap.setObjectName("checkbox_swap")
        self.horizontalLayout_5.addWidget(self.checkbox_swap)
        self.verticalLayout_3.addLayout(self.horizontalLayout_5)
        self.pushbutton_autodetection = QtWidgets.QPushButton(self.splitter)
        self.pushbutton_autodetection.setObjectName("pushbutton_autodetection")
        self.tabWidget_2 = QtWidgets.QTabWidget(self.splitter)
        self.tabWidget_2.setObjectName("tabWidget_2")
        self.tab_PValues = QtWidgets.QWidget()
        self.tab_PValues.setObjectName("tab_PValues")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.tab_PValues)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.txt_PixelValue_X = QtWidgets.QLabel(self.tab_PValues)
        self.txt_PixelValue_X.setObjectName("txt_PixelValue_X")
        self.horizontalLayout_3.addWidget(self.txt_PixelValue_X)
        self.UserInput_PixelValue_X = QtWidgets.QLineEdit(self.tab_PValues)
        self.UserInput_PixelValue_X.setObjectName("UserInput_PixelValue_X")
        self.horizontalLayout_3.addWidget(self.UserInput_PixelValue_X)
        self.txt_PixelValue_Y = QtWidgets.QLabel(self.tab_PValues)
        self.txt_PixelValue_Y.setObjectName("txt_PixelValue_Y")
        self.horizontalLayout_3.addWidget(self.txt_PixelValue_Y)
        self.UserInput_PixelValue_Y = QtWidgets.QLineEdit(self.tab_PValues)
        self.UserInput_PixelValue_Y.setObjectName("UserInput_PixelValue_Y")
        self.horizontalLayout_3.addWidget(self.UserInput_PixelValue_Y)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.gridLayout_5 = QtWidgets.QGridLayout()
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.UserInput_PixelValue_B = QtWidgets.QLineEdit(self.tab_PValues)
        self.UserInput_PixelValue_B.setObjectName("UserInput_PixelValue_B")
        self.gridLayout_5.addWidget(self.UserInput_PixelValue_B, 2, 1, 1, 1)
        self.txt_PixelValue_G = QtWidgets.QLabel(self.tab_PValues)
        self.txt_PixelValue_G.setObjectName("txt_PixelValue_G")
        self.gridLayout_5.addWidget(self.txt_PixelValue_G, 1, 0, 1, 1)
        self.txt_PixelValue_R = QtWidgets.QLabel(self.tab_PValues)
        self.txt_PixelValue_R.setObjectName("txt_PixelValue_R")
        self.gridLayout_5.addWidget(self.txt_PixelValue_R, 0, 0, 1, 1)
        self.UserInput_PixelValue_G = QtWidgets.QLineEdit(self.tab_PValues)
        self.UserInput_PixelValue_G.setObjectName("UserInput_PixelValue_G")
        self.gridLayout_5.addWidget(self.UserInput_PixelValue_G, 1, 1, 1, 1)
        self.UserInput_PixelValue_R = QtWidgets.QLineEdit(self.tab_PValues)
        self.UserInput_PixelValue_R.setObjectName("UserInput_PixelValue_R")
        self.gridLayout_5.addWidget(self.UserInput_PixelValue_R, 0, 1, 1, 1)
        self.txt_PixelValue_B = QtWidgets.QLabel(self.tab_PValues)
        self.txt_PixelValue_B.setObjectName("txt_PixelValue_B")
        self.gridLayout_5.addWidget(self.txt_PixelValue_B, 2, 0, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout_5)
        self.gridLayout_2.addLayout(self.verticalLayout, 0, 0, 1, 1)
        self.tabWidget_2.addTab(self.tab_PValues, "")
        self.gridLayout_6.addWidget(self.splitter, 0, 1, 1, 1)
        self.scrollArea = QtWidgets.QScrollArea(self.widget)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 1158, 144))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.gridLayout = QtWidgets.QGridLayout(self.scrollAreaWidgetContents)
        self.gridLayout.setObjectName("gridLayout")
        self.mdiArea = QtWidgets.QMdiArea(self.scrollAreaWidgetContents)
        self.mdiArea.setObjectName("mdiArea")
        self.gridLayout.addWidget(self.mdiArea, 0, 0, 1, 1)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.gridLayout_6.addWidget(self.scrollArea, 1, 0, 1, 2)
        self.scrollArea_2 = QtWidgets.QScrollArea(self.widget)
        self.scrollArea_2.setWidgetResizable(True)
        self.scrollArea_2.setObjectName("scrollArea_2")
        self.scrollAreaWidgetContents_2 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 722, 633))
        self.scrollAreaWidgetContents_2.setObjectName("scrollAreaWidgetContents_2")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.scrollAreaWidgetContents_2)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_img = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.label_img.setText("")
        self.label_img.setObjectName("label_img")
        self.gridLayout_3.addWidget(self.label_img, 0, 0, 1, 1)
        self.scrollArea_2.setWidget(self.scrollAreaWidgetContents_2)
        self.gridLayout_6.addWidget(self.scrollArea_2, 0, 0, 1, 1)
        self.gridLayout_4.addWidget(self.widget, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1196, 25))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuEdit = QtWidgets.QMenu(self.menubar)
        self.menuEdit.setObjectName("menuEdit")
        self.menuImages = QtWidgets.QMenu(self.menubar)
        self.menuImages.setObjectName("menuImages")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.toolBar = QtWidgets.QToolBar(MainWindow)
        self.toolBar.setStyleSheet("selection-color: rgb(7, 148, 229);")
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.actionOpen = QtWidgets.QAction(MainWindow)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/open/open.qrc"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon.addPixmap(QtGui.QPixmap(":/open/open.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        icon.addPixmap(QtGui.QPixmap(":/open/open.png"), QtGui.QIcon.Active, QtGui.QIcon.Off)
        icon.addPixmap(QtGui.QPixmap(":/open/open.png"), QtGui.QIcon.Active, QtGui.QIcon.On)
        icon.addPixmap(QtGui.QPixmap(":/open/open.png"), QtGui.QIcon.Selected, QtGui.QIcon.Off)
        icon.addPixmap(QtGui.QPixmap(":/open/open.png"), QtGui.QIcon.Selected, QtGui.QIcon.On)
        self.actionOpen.setIcon(icon)
        self.actionOpen.setObjectName("actionOpen")
        self.actionSave_As = QtWidgets.QAction(MainWindow)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/save/save.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionSave_As.setIcon(icon1)
        self.actionSave_As.setObjectName("actionSave_As")
        self.actionExit = QtWidgets.QAction(MainWindow)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/exit/exit.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionExit.setIcon(icon2)
        self.actionExit.setObjectName("actionExit")
        self.actionZoom_in = QtWidgets.QAction(MainWindow)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/zoomin/zoomin.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionZoom_in.setIcon(icon3)
        self.actionZoom_in.setObjectName("actionZoom_in")
        self.actionZoom_out = QtWidgets.QAction(MainWindow)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/zoomout/zoomout.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionZoom_out.setIcon(icon4)
        self.actionZoom_out.setObjectName("actionZoom_out")
        self.actionHelp = QtWidgets.QAction(MainWindow)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/help/help.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionHelp.setIcon(icon5)
        self.actionHelp.setObjectName("actionHelp")
        self.actionAbout = QtWidgets.QAction(MainWindow)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/about/about.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionAbout.setIcon(icon6)
        self.actionAbout.setObjectName("actionAbout")
        self.menuFile.addAction(self.actionOpen)
        self.menuFile.addAction(self.actionSave_As)
        self.menuFile.addAction(self.actionExit)
        self.menuEdit.addAction(self.actionZoom_in)
        self.menuEdit.addAction(self.actionZoom_out)
        self.menuImages.addAction(self.actionHelp)
        self.menuImages.addAction(self.actionAbout)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuEdit.menuAction())
        self.menubar.addAction(self.menuImages.menuAction())
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionOpen)
        self.toolBar.addAction(self.actionSave_As)
        self.toolBar.addAction(self.actionZoom_in)
        self.toolBar.addAction(self.actionZoom_out)
        self.toolBar.addAction(self.actionHelp)
        self.toolBar.addAction(self.actionAbout)
        self.toolBar.addAction(self.actionExit)

        self.retranslateUi(MainWindow)
        self.tabWidget_4.setCurrentIndex(0)
        self.comb_format.setCurrentIndex(0)
        self.tabWidget_3.setCurrentIndex(0)
        self.tabWidget.setCurrentIndex(0)
        self.tabWidget_2.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.comb_format.setItemText(0, _translate("MainWindow", "YUYV"))
        self.comb_format.setItemText(1, _translate("MainWindow", "UYVY"))
        self.comb_format.setItemText(2, _translate("MainWindow", "YVYU"))
        self.comb_format.setItemText(3, _translate("MainWindow", "VYUY"))
        self.comb_format.setItemText(4, _translate("MainWindow", "BGR3"))
        self.comb_format.setItemText(5, _translate("MainWindow", "RGB3"))
        self.comb_format.setItemText(6, _translate("MainWindow", "XR24"))
        self.comb_format.setItemText(7, _translate("MainWindow", "RGBP"))
        self.tabWidget_4.setTabText(self.tabWidget_4.indexOf(self.tab_3), _translate("MainWindow", "Format"))
        self.LineEdit_width.setText(_translate("MainWindow", "400"))
        self.label.setText(_translate("MainWindow", "x"))
        self.LineEdit_height.setText(_translate("MainWindow", "400"))
        self.apply_button.setText(_translate("MainWindow", "Apply"))
        self.tabWidget_3.setTabText(self.tabWidget_3.indexOf(self.tab_2), _translate("MainWindow", "Size"))
        self.radiobutton_be.setText(_translate("MainWindow", "BE"))
        self.radiobutton_le.setText(_translate("MainWindow", "LE"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Endianess"))
        self.group_rgb.setTitle(_translate("MainWindow", "Channels"))
        self.checkbox_r.setText(_translate("MainWindow", "R"))
        self.checkbox_g.setText(_translate("MainWindow", "G"))
        self.checkbox_b.setText(_translate("MainWindow", "B"))
        self.checkbox_y.setText(_translate("MainWindow", "Y"))
        self.checkbox_u.setText(_translate("MainWindow", "U"))
        self.checkbox_v.setText(_translate("MainWindow", "V"))
        self.checkbox__a_yuv.setText(_translate("MainWindow", "A"))
        self.checkbox_swap.setText(_translate("MainWindow", "Swap UV"))
        self.pushbutton_autodetection.setText(_translate("MainWindow", "AutoDetection"))
        self.txt_PixelValue_X.setText(_translate("MainWindow", "X:"))
        self.txt_PixelValue_Y.setText(_translate("MainWindow", "Y:"))
        self.txt_PixelValue_G.setText(_translate("MainWindow", "G:"))
        self.txt_PixelValue_R.setText(_translate("MainWindow", "R:"))
        self.txt_PixelValue_B.setText(_translate("MainWindow", "B:"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_PValues), _translate("MainWindow", "Pixel values"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuEdit.setTitle(_translate("MainWindow", "Edit"))
        self.menuImages.setTitle(_translate("MainWindow", "info"))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar"))
        self.actionOpen.setText(_translate("MainWindow", "Open"))
        self.actionOpen.setShortcut(_translate("MainWindow", "Ctrl+O"))
        self.actionSave_As.setText(_translate("MainWindow", "Save_As"))
        self.actionSave_As.setShortcut(_translate("MainWindow", "Ctrl+S"))
        self.actionExit.setText(_translate("MainWindow", "Exit"))
        self.actionExit.setShortcut(_translate("MainWindow", "Ctrl+Q"))
        self.actionZoom_in.setText(_translate("MainWindow", "Zoom_in"))
        self.actionZoom_in.setShortcut(_translate("MainWindow", "Ctrl+="))
        self.actionZoom_out.setText(_translate("MainWindow", "Zoom_out"))
        self.actionZoom_out.setShortcut(_translate("MainWindow", "Ctrl+-"))
        self.actionHelp.setText(_translate("MainWindow", "Help"))
        self.actionHelp.setShortcut(_translate("MainWindow", "Ctrl+H"))
        self.actionAbout.setText(_translate("MainWindow", "About"))
        self.actionAbout.setShortcut(_translate("MainWindow", "Ctrl+A"))

import about_rc
import exit_rc
import help_rc
import open_rc
import save_rc
import zoomin_rc
import zoomout_rc

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

