from uitest import Ui_MainWindow 
from PyQt5.QtWidgets import QMainWindow
from PyQt5 import QtCore, QtGui, QtWidgets, uic

import sys
import os


class Ui_MainWindow(object):
	def setupUi(self, MainWindow):
  	  MainWindow.setObjectName("MainWindow")
  	  MainWindow.resize(800, 600)
   	  self.centralwidget = QtWidgets.QWidget(MainWindow)
   	  self.centralwidget.setObjectName("centralwidget")
   	  self.pushButton = QtWidgets.QPushButton(self.centralwidget)
  	  self.pushButton.setGeometry(QtCore.QRect(120, 330, 151, 71))
  	  self.pushButton.setObjectName("pushButton")
    	  self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
  	  self.pushButton_2.setGeometry(QtCore.QRect(360, 330, 151, 71))
    	  self.pushButton_2.setObjectName("pushButton_2")
    	  self.textEdit = QtWidgets.QTextEdit(self.centralwidget)
    	  self.textEdit.setGeometry(QtCore.QRect(160, 80, 321, 181))
      	  self.textEdit.setObjectName("textEdit")
          MainWindow.setCentralWidget(self.centralwidget)
          self.menubar = QtWidgets.QMenuBar(MainWindow)
          self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
          self.menubar.setObjectName("menubar")
    	  MainWindow.setMenuBar(self.menubar)
    	  self.statusbar = QtWidgets.QStatusBar(MainWindow)
    self.statusbar.setObjectName("statusbar")
    MainWindow.setStatusBar(self.statusbar)
    self.toolBar1 = QtWidgets.QToolBar(MainWindow)
    sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
    sizePolicy.setHorizontalStretch(0)
    sizePolicy.setVerticalStretch(0)
    sizePolicy.setHeightForWidth(self.toolBar1.sizePolicy().hasHeightForWidth())
    self.toolBar1.setSizePolicy(sizePolicy)
    font = QtGui.QFont()
    font.setPointSize(14)
    self.toolBar1.setFont(font)
    self.toolBar1.setObjectName("toolBar1")
    MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar1)
    self.toolBar = QtWidgets.QToolBar(MainWindow)
    font = QtGui.QFont()
    font.setPointSize(12)
    self.toolBar.setFont(font)
    self.toolBar.setObjectName("toolBar")
    MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
    MainWindow.insertToolBarBreak(self.toolBar)
    self.toolBar_2 = QtWidgets.QToolBar(MainWindow)
    font = QtGui.QFont()
    font.setPointSize(10)
    self.toolBar_2.setFont(font)
    self.toolBar_2.setObjectName("toolBar_2")
    MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar_2)
    MainWindow.insertToolBarBreak(self.toolBar_2)
    self.Action1 = QtWidgets.QAction(MainWindow)
    self.Action1.setObjectName("Action1")
    self.Action2 = QtWidgets.QAction(MainWindow)
    self.Action2.setObjectName("Action2")
    self.Action3 = QtWidgets.QAction(MainWindow)
    self.Action3.setObjectName("Action3")
    self.Action4 = QtWidgets.QAction(MainWindow)
    self.Action4.setObjectName("Action4")
    self.Action5 = QtWidgets.QAction(MainWindow)
    self.Action5.setObjectName("Action5")
    self.Action6 = QtWidgets.QAction(MainWindow)
    self.Action6.setObjectName("Action6")
    self.Action7 = QtWidgets.QAction(MainWindow)
    self.Action7.setObjectName("Action7")
    self.Action8 = QtWidgets.QAction(MainWindow)
    self.Action8.setObjectName("Action8")
    self.Action9 = QtWidgets.QAction(MainWindow)
    self.Action9.setObjectName("Action9")
    self.toolBar1.addAction(self.Action1)
    self.toolBar1.addSeparator()
    self.toolBar1.addAction(self.Action2)
    self.toolBar1.addSeparator()
    self.toolBar1.addAction(self.Action3)
    self.toolBar.addAction(self.Action4)
    self.toolBar.addSeparator()
    self.toolBar.addAction(self.Action5)
    self.toolBar.addSeparator()
    self.toolBar.addAction(self.Action6)
    self.toolBar_2.addAction(self.Action7)
    self.toolBar_2.addSeparator()
    self.toolBar_2.addAction(self.Action8)
    self.toolBar_2.addSeparator()
    self.toolBar_2.addAction(self.Action9)

    self.retranslateUi(MainWindow)
    QtCore.QMetaObject.connectSlotsByName(MainWindow)

def retranslateUi(self, MainWindow):
    _translate = QtCore.QCoreApplication.translate
    MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
    self.pushButton.setText(_translate("MainWindow", "PushButton"))
    self.pushButton_2.setText(_translate("MainWindow", "PushButton"))
    self.toolBar1.setWindowTitle(_translate("MainWindow", "toolBar"))
    self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar"))
    self.toolBar_2.setWindowTitle(_translate("MainWindow", "toolBar_2"))
    self.Action1.setText(_translate("MainWindow", "Action1"))
    self.Action2.setText(_translate("MainWindow", "Action2"))
    self.Action3.setText(_translate("MainWindow", "Action3"))
    self.Action4.setText(_translate("MainWindow", "Action4"))
    self.Action5.setText(_translate("MainWindow", "Action5"))
    self.Action6.setText(_translate("MainWindow", "Action6"))
    self.Action7.setText(_translate("MainWindow", "Action7"))
    self.Action8.setText(_translate("MainWindow", "Action8"))
    self.Action9.setText(_translate("MainWindow", "Action9"))

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()

    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)

    MainWindow.show()
    sys.exit(app.exec_())


