#!/usr/bin/env python3
# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'second.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1332, 829)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget_2 = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget_2.setGeometry(QtCore.QRect(1050, 560, 261, 151))
        self.tabWidget_2.setObjectName("tabWidget_2")
        self.tab_PValues = QtWidgets.QWidget()
        self.tab_PValues.setObjectName("tab_PValues")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.tab_PValues)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.txt_PixelValue_X = QtWidgets.QLabel(self.tab_PValues)
        self.txt_PixelValue_X.setObjectName("txt_PixelValue_X")
        self.horizontalLayout_3.addWidget(self.txt_PixelValue_X)
        self.UserInput_PixelValue_X = QtWidgets.QLineEdit(self.tab_PValues)
        self.UserInput_PixelValue_X.setObjectName("UserInput_PixelValue_X")
        self.horizontalLayout_3.addWidget(self.UserInput_PixelValue_X)
        self.txt_PixelValue_Y = QtWidgets.QLabel(self.tab_PValues)
        self.txt_PixelValue_Y.setObjectName("txt_PixelValue_Y")
        self.horizontalLayout_3.addWidget(self.txt_PixelValue_Y)
        self.UserInput_PixelValue_Y = QtWidgets.QLineEdit(self.tab_PValues)
        self.UserInput_PixelValue_Y.setObjectName("UserInput_PixelValue_Y")
        self.horizontalLayout_3.addWidget(self.UserInput_PixelValue_Y)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.gridLayout_5 = QtWidgets.QGridLayout()
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.UserInput_PixelValue_B = QtWidgets.QLineEdit(self.tab_PValues)
        self.UserInput_PixelValue_B.setObjectName("UserInput_PixelValue_B")
        self.gridLayout_5.addWidget(self.UserInput_PixelValue_B, 2, 1, 1, 1)
        self.txt_PixelValue_G = QtWidgets.QLabel(self.tab_PValues)
        self.txt_PixelValue_G.setObjectName("txt_PixelValue_G")
        self.gridLayout_5.addWidget(self.txt_PixelValue_G, 1, 0, 1, 1)
        self.txt_PixelValue_R = QtWidgets.QLabel(self.tab_PValues)
        self.txt_PixelValue_R.setObjectName("txt_PixelValue_R")
        self.gridLayout_5.addWidget(self.txt_PixelValue_R, 0, 0, 1, 1)
        self.UserInput_PixelValue_G = QtWidgets.QLineEdit(self.tab_PValues)
        self.UserInput_PixelValue_G.setObjectName("UserInput_PixelValue_G")
        self.gridLayout_5.addWidget(self.UserInput_PixelValue_G, 1, 1, 1, 1)
        self.UserInput_PixelValue_R = QtWidgets.QLineEdit(self.tab_PValues)
        self.UserInput_PixelValue_R.setObjectName("UserInput_PixelValue_R")
        self.gridLayout_5.addWidget(self.UserInput_PixelValue_R, 0, 1, 1, 1)
        self.txt_PixelValue_B = QtWidgets.QLabel(self.tab_PValues)
        self.txt_PixelValue_B.setObjectName("txt_PixelValue_B")
        self.gridLayout_5.addWidget(self.txt_PixelValue_B, 2, 0, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout_5)
        self.gridLayout_2.addLayout(self.verticalLayout, 0, 0, 1, 1)
        self.tabWidget_2.addTab(self.tab_PValues, "")
        self.layoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget_2.setGeometry(QtCore.QRect(1059, 189, 191, 50))
        self.layoutWidget_2.setObjectName("layoutWidget_2")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.layoutWidget_2)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_endlianess = QtWidgets.QLabel(self.layoutWidget_2)
        self.label_endlianess.setObjectName("label_endlianess")
        self.verticalLayout_4.addWidget(self.label_endlianess)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.radiobutton_be = QtWidgets.QRadioButton(self.layoutWidget_2)
        self.radiobutton_be.setObjectName("radiobutton_be")
        self.horizontalLayout.addWidget(self.radiobutton_be)
        self.radiobutton_le = QtWidgets.QRadioButton(self.layoutWidget_2)
        self.radiobutton_le.setObjectName("radiobutton_le")
        self.horizontalLayout.addWidget(self.radiobutton_le)
        self.verticalLayout_4.addLayout(self.horizontalLayout)
        self.layoutWidget_3 = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget_3.setGeometry(QtCore.QRect(1060, 361, 191, 25))
        self.layoutWidget_3.setObjectName("layoutWidget_3")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.layoutWidget_3)
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.checkbox__a_yuv = QtWidgets.QCheckBox(self.layoutWidget_3)
        self.checkbox__a_yuv.setObjectName("checkbox__a_yuv")
        self.horizontalLayout_6.addWidget(self.checkbox__a_yuv)
        self.checkbox_swapui_yuv = QtWidgets.QCheckBox(self.layoutWidget_3)
        self.checkbox_swapui_yuv.setObjectName("checkbox_swapui_yuv")
        self.horizontalLayout_6.addWidget(self.checkbox_swapui_yuv)
        self.layoutWidget_4 = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget_4.setGeometry(QtCore.QRect(1059, 19, 191, 50))
        self.layoutWidget_4.setObjectName("layoutWidget_4")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.layoutWidget_4)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_format = QtWidgets.QLabel(self.layoutWidget_4)
        self.label_format.setObjectName("label_format")
        self.verticalLayout_2.addWidget(self.label_format, 0, QtCore.Qt.AlignVCenter)
        self.comb_format = QtWidgets.QComboBox(self.layoutWidget_4)
        self.comb_format.setObjectName("comb_format")
        self.comb_format.addItem("")
        self.comb_format.addItem("")
        self.comb_format.addItem("")
        self.comb_format.addItem("")
        self.verticalLayout_2.addWidget(self.comb_format)
        self.layoutWidget_5 = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget_5.setGeometry(QtCore.QRect(1059, 289, 191, 25))
        self.layoutWidget_5.setObjectName("layoutWidget_5")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.layoutWidget_5)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.checkbox_r = QtWidgets.QCheckBox(self.layoutWidget_5)
        self.checkbox_r.setObjectName("checkbox_r")
        self.horizontalLayout_4.addWidget(self.checkbox_r)
        self.checkbox_g = QtWidgets.QCheckBox(self.layoutWidget_5)
        self.checkbox_g.setObjectName("checkbox_g")
        self.horizontalLayout_4.addWidget(self.checkbox_g)
        self.checkbox_b = QtWidgets.QCheckBox(self.layoutWidget_5)
        self.checkbox_b.setObjectName("checkbox_b")
        self.horizontalLayout_4.addWidget(self.checkbox_b)
        self.pushbutton_autodetection = QtWidgets.QPushButton(self.centralwidget)
        self.pushbutton_autodetection.setGeometry(QtCore.QRect(1059, 419, 191, 31))
        self.pushbutton_autodetection.setObjectName("pushbutton_autodetection")
        self.layoutWidget_6 = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget_6.setGeometry(QtCore.QRect(1061, 99, 191, 61))
        self.layoutWidget_6.setObjectName("layoutWidget_6")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.layoutWidget_6)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_size = QtWidgets.QLabel(self.layoutWidget_6)
        self.label_size.setObjectName("label_size")
        self.verticalLayout_5.addWidget(self.label_size)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.lineedit_size1 = QtWidgets.QLineEdit(self.layoutWidget_6)
        self.lineedit_size1.setObjectName("lineedit_size1")
        self.horizontalLayout_2.addWidget(self.lineedit_size1)
        self.label_x = QtWidgets.QLabel(self.layoutWidget_6)
        self.label_x.setObjectName("label_x")
        self.horizontalLayout_2.addWidget(self.label_x)
        self.lineedit_size2 = QtWidgets.QLineEdit(self.layoutWidget_6)
        self.lineedit_size2.setObjectName("lineedit_size2")
        self.horizontalLayout_2.addWidget(self.lineedit_size2)
        self.verticalLayout_5.addLayout(self.horizontalLayout_2)
        self.layoutWidget_7 = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget_7.setGeometry(QtCore.QRect(1060, 330, 191, 25))
        self.layoutWidget_7.setObjectName("layoutWidget_7")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.layoutWidget_7)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.checkbox_y = QtWidgets.QCheckBox(self.layoutWidget_7)
        self.checkbox_y.setObjectName("checkbox_y")
        self.horizontalLayout_5.addWidget(self.checkbox_y)
        self.checkbox_u = QtWidgets.QCheckBox(self.layoutWidget_7)
        self.checkbox_u.setObjectName("checkbox_u")
        self.horizontalLayout_5.addWidget(self.checkbox_u)
        self.checkbox_v = QtWidgets.QCheckBox(self.layoutWidget_7)
        self.checkbox_v.setObjectName("checkbox_v")
        self.horizontalLayout_5.addWidget(self.checkbox_v)
        self.label_channels_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_channels_2.setGeometry(QtCore.QRect(1060, 270, 67, 17))
        self.label_channels_2.setObjectName("label_channels_2")
        self.mdiArea = QtWidgets.QMdiArea(self.centralwidget)
        self.mdiArea.setGeometry(QtCore.QRect(11, 11, 1031, 251))
        self.mdiArea.setObjectName("mdiArea")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(20, 270, 1021, 451))
        self.label.setText("")
        self.label.setObjectName("label")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1332, 22))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuEdit = QtWidgets.QMenu(self.menubar)
        self.menuEdit.setObjectName("menuEdit")
        self.menuImages = QtWidgets.QMenu(self.menubar)
        self.menuImages.setObjectName("menuImages")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.toolBar = QtWidgets.QToolBar(MainWindow)
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.actionNew = QtWidgets.QAction(MainWindow)
        self.actionNew.setObjectName("actionNew")
        self.actionOpen = QtWidgets.QAction(MainWindow)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/open/open.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionOpen.setIcon(icon)
        self.actionOpen.setObjectName("actionOpen")
        self.actionZoom_in = QtWidgets.QAction(MainWindow)
        self.actionZoom_in.setCheckable(False)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/zoomin/zoomin.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionZoom_in.setIcon(icon1)
        self.actionZoom_in.setIconVisibleInMenu(False)
        self.actionZoom_in.setObjectName("actionZoom_in")
        self.actionZoom_Out = QtWidgets.QAction(MainWindow)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/zoomout/zoomout.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionZoom_Out.setIcon(icon2)
        self.actionZoom_Out.setObjectName("actionZoom_Out")
        self.actionSave_As = QtWidgets.QAction(MainWindow)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/save/save.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionSave_As.setIcon(icon3)
        self.actionSave_As.setObjectName("actionSave_As")
        self.actionExit = QtWidgets.QAction(MainWindow)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/exit/exit.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionExit.setIcon(icon4)
        self.actionExit.setObjectName("actionExit")
        self.actionHelp = QtWidgets.QAction(MainWindow)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/help/help.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionHelp.setIcon(icon5)
        self.actionHelp.setObjectName("actionHelp")
        self.actionAbout = QtWidgets.QAction(MainWindow)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/about/about.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionAbout.setIcon(icon6)
        self.actionAbout.setObjectName("actionAbout")
        self.menuFile.addAction(self.actionOpen)
        self.menuFile.addAction(self.actionSave_As)
        self.menuFile.addAction(self.actionExit)
        self.menuEdit.addAction(self.actionZoom_in)
        self.menuEdit.addAction(self.actionZoom_Out)
        self.menuImages.addAction(self.actionHelp)
        self.menuImages.addAction(self.actionAbout)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuEdit.menuAction())
        self.menubar.addAction(self.menuImages.menuAction())
        self.toolBar.addAction(self.actionOpen)
        self.toolBar.addAction(self.actionSave_As)
        self.toolBar.addAction(self.actionZoom_in)
        self.toolBar.addAction(self.actionZoom_Out)
        self.toolBar.addAction(self.actionExit)
        self.toolBar.addAction(self.actionHelp)
        self.toolBar.addAction(self.actionAbout)
        self.toolBar.addSeparator()

        self.retranslateUi(MainWindow)
        self.tabWidget_2.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.txt_PixelValue_X.setText(_translate("MainWindow", "X:"))
        self.txt_PixelValue_Y.setText(_translate("MainWindow", "Y:"))
        self.txt_PixelValue_G.setText(_translate("MainWindow", "G:"))
        self.txt_PixelValue_R.setText(_translate("MainWindow", "R:"))
        self.txt_PixelValue_B.setText(_translate("MainWindow", "B:"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_PValues), _translate("MainWindow", "Pixel values"))
        self.label_endlianess.setText(_translate("MainWindow", "Endianess:"))
        self.radiobutton_be.setText(_translate("MainWindow", "BE"))
        self.radiobutton_le.setText(_translate("MainWindow", "LE"))
        self.checkbox__a_yuv.setText(_translate("MainWindow", "A"))
        self.checkbox_swapui_yuv.setText(_translate("MainWindow", "Swap UV"))
        self.label_format.setText(_translate("MainWindow", "Format:"))
        self.comb_format.setItemText(0, _translate("MainWindow", "YUYV"))
        self.comb_format.setItemText(1, _translate("MainWindow", "UYVY"))
        self.comb_format.setItemText(2, _translate("MainWindow", "YVYU"))
        self.comb_format.setItemText(3, _translate("MainWindow", "VYUY"))
        self.checkbox_r.setText(_translate("MainWindow", "R"))
        self.checkbox_g.setText(_translate("MainWindow", "G"))
        self.checkbox_b.setText(_translate("MainWindow", "B"))
        self.pushbutton_autodetection.setText(_translate("MainWindow", "AutoDetection"))
        self.label_size.setText(_translate("MainWindow", "Size:"))
        self.label_x.setText(_translate("MainWindow", " X"))
        self.checkbox_y.setText(_translate("MainWindow", "Y"))
        self.checkbox_u.setText(_translate("MainWindow", "U"))
        self.checkbox_v.setText(_translate("MainWindow", "V"))
        self.label_channels_2.setText(_translate("MainWindow", "Channels:"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuEdit.setTitle(_translate("MainWindow", "View"))
        self.menuImages.setTitle(_translate("MainWindow", "Help"))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar"))
        self.actionNew.setText(_translate("MainWindow", "New"))
        self.actionOpen.setText(_translate("MainWindow", "Open"))
        self.actionOpen.setShortcut(_translate("MainWindow", "Ctrl+O"))
        self.actionZoom_in.setText(_translate("MainWindow", "Zoom In"))
        self.actionZoom_in.setShortcut(_translate("MainWindow", "Ctrl++"))
        self.actionZoom_Out.setText(_translate("MainWindow", "Zoom Out"))
        self.actionZoom_Out.setShortcut(_translate("MainWindow", "Ctrl+-"))
        self.actionSave_As.setText(_translate("MainWindow", "Save As ..."))
        self.actionSave_As.setShortcut(_translate("MainWindow", "Ctrl+S"))
        self.actionExit.setText(_translate("MainWindow", "Exit"))
        self.actionExit.setShortcut(_translate("MainWindow", "Ctrl+Q"))
        self.actionHelp.setText(_translate("MainWindow", "Help"))
        self.actionHelp.setShortcut(_translate("MainWindow", "Ctrl+H"))
        self.actionAbout.setText(_translate("MainWindow", "About"))
        self.actionAbout.setShortcut(_translate("MainWindow", "Ctrl+A"))

